// <auto-generated />
using FranceTravail.AppDataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FranceTravail.Migrations
{
    [DbContext(typeof(JobsDatabaseSQLiteContext))]
    partial class JobsDatabaseSQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FranceTravail.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntrepriseNom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LieuDeTravail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlPostulation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
